# -*- coding: utf-8 -*-
"""Schedule_mrec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6pEWBuvHA37lJO4uso9kUUxiOcQu26c
"""

#!pip install -q -U schedule

import pandas as pd
import schedule
import time
from datetime import datetime

def job_with_argument(name):
    now = datetime.now()
    fecha_ultima_revision = now.strftime('Día :%d-%m-%Y, Hora: %H:%M:%S')
    print(f"{name}: {fecha_ultima_revision}")
    #Leer el archivo MOVIERECOMMENDATION desde la última línea leída con anterioridad
    #Call API VICTORización (dentro escribe salida a excel JUAN: https://docs.google.com/spreadsheets/d/1T2H33PS-I0g0PhQyYblMrYcc8K3FSLbEkonV0VDYfwI/edit?gid=0#gid=0)
    #Guardar en un archivo en que línea del excel MOVIERECOMMENDATION quedó:
    #Escribir Cuántos llegaron (Pantalla Streamlit)
    #Call API Mailing

schedule.every(10).seconds.do(job_with_argument, name="MovieRec")

while True:
    schedule.run_pending()
    time.sleep(1)

# Carga el archivo de Excel en un DataFrame
def cargar_excel(ruta_archivo):
    return pd.read_excel(ruta_archivo)

# Comprueba si hay nuevas filas en el archivo de Excel
def comprobar_nuevas_filas(ruta_archivo, df_anterior):
    df_actual = cargar_excel(ruta_archivo)
    if len(df_actual) > len(df_anterior):
        print("Hay nuevas filas!")
        # Aquí puedes agregar código para procesar las nuevas filas
    return df_actual

# Programa la tarea para ejecutar cada cierto tiempo
def programar_tarea(ruta_archivo, intervalo):
    df_anterior = cargar_excel(ruta_archivo)
    schedule.every(intervalo).seconds.do(comprobar_nuevas_filas, ruta_archivo, df_anterior)

# Ejecuta la tarea programada
def ejecutar_tarea():
    while True:
        schedule.run_pending()
        time.sleep(1)

# Ruta del archivo de Excel
#ruta_archivo = "ruta/a/tu/archivo.xlsx"

# Intervalo de tiempo para comprobar nuevas filas (en segundos)
#intervalo = 60  # 1 minuto

# Programa la tarea
#programar_tarea(ruta_archivo, intervalo)

# Ejecuta la tarea
#ejecutar_tarea()